name: A branch workflow

on:
  push:
    branches:
      - '!main'

jobs:
  tests:
    uses: ./.github/workflows/unit_tests.yaml
  deploy:
    uses: ./.github/workflows/deployment.yaml
    needs: [tests]