name: Container Build

on:
  workflow_call:
    inputs:
      container_name:
        description: 'A friendly name of the container we are building.'
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "Building ${{ inputs.container_name }} from ${GITHUB_REF_NAME}"
