name: Container Build

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "Building ${{ env.container_name }} from ${GITHUB_REF_NAME}"
