name: Cloud Deployments

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "Deploying to Cloud"