name: The main workflow

on:
  push:

jobs:
  conditional:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/conditional_invocation.yaml
  tests:
    needs: [conditional]
    if: always()
    uses: ./.github/workflows/unit_tests.yaml
  deploy:
    uses: ./.github/workflows/deployment.yaml
    needs: [tests]
  build_one:
    uses: ./.github/workflows/container_build.yaml
    with:
      container_name: "Container One"
