name: The main workflow

on:
  push:

jobs:
  tests:
    uses: ./.github/workflows/unit_tests.yaml
    with:
      username: $GITHUB_ACTOR
  deploy:
    uses: ./.github/workflows/deployment.yaml
    with:
      username: $GITHUB_ACTOR