name: Tests and Checks

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  run-the-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: "*"

    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          echo "Running unit tests"